---
version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  springboot:
    expose: 
      - "8080"
    image: "janosch/springboot-mongo"
    ports: 
      - "8080:8080"